name: xiaoguzaijiu
on:
  workflow_dispatch:
  schedule:
    - cron: '6 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaoguzaijiu
        env:
          we6884: ${{ secrets.we6884 }}
        run: |
          echo $we6884 | jq -r .pfmxt41593 | /bin/bash
          echo $sjiff72 | jq -r .cqw49789 | /bin/bash
          echo $gl88 | jq -r .uoh774 | /bin/bash
          echo $cl56923 | jq -r .yggz8 | /bin/bash
          echo $qalju175 | jq -r .ocivh4 | /bin/bash
          echo $lkyq9 | jq -r .na35 | /bin/bash
          echo $dmfi3 | jq -r .n5 | /bin/bash
          echo $siyc5 | jq -r .jszhf6 | /bin/bash
          echo $bcuc81 | jq -r .xn72280 | /bin/bash
          echo $axz0 | jq -r .hbk310 | /bin/bash
          echo $zqbfh94 | jq -r .lxxde4 | /bin/bash
          echo $hk3 | jq -r .pwaj54 | /bin/bash
          echo $gg651 | jq -r .eas7254 | /bin/bash

